apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: customapp
  template:
    metadata:
      labels:
        app: customapp
    spec:
      containers:
      - name: nginx
        image: shrijo/customapp
        ports:
        - containerPort: 80

