apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-dep-new
spec:
  replicas: 2
  selector:
    matchLabels:
      app: newcustomapp  # Change to a new label
  template:
    metadata:
      labels:
        app: newcustomapp  # Change to a new label
    spec:
      containers:
      - name: nginx
        image: shrijo/customapp
        ports:
        - containerPort: 80

